export const wineries = [
  {
    name: "Axe Hill Winery",
    coords: "33°30′58″S 21°41′22″E",
    location: "Calitszdorp",
    key: "axehillwinery",
  },
  {
    name: "Glenelly Estate",
    coords: "33°55′12.56″S 18°52′43.87″E",
    location: "Stellenbosch",
    key: "glenellyestate",
  },
  {
    name: "Alheit Vinyards",
    coords: "34°20′33″S 19°18′10″E",
    location: "Hermanus",
    key: "alheitvinyards",
  },
  {
    name: "Boplaas Winery and Distillery",
    coords: "33°32′07″S 21°41′01″E",
    location: "Calitszdorp",
    key: "boplaaswineryanddistillery",
  },
  {
    name: "Calitzdorp Wine Cellar",
    coords: "33°32′17″S 21°41′10″E",
    location: "Calitszdorp",
    key: "calitzdorpwinecellar",
  },
  {
    name: "De Krans Wines",
    coords: "33°32′24″S 21°41′03″E",
    location: "Calitszdorp",
    key: "dekranswines",
  },
  {
    name: "Ambeloui",
    coords: "34.033434°S 18.366283°E",
    location: "Constantia",
    key: "ambeloui",
  },
  {
    name: "Beau Constantia",
    coords: "",
    location: "Constantia",
    key: "beauconstantia",
  },
  {
    name: "Buitenverwachting",
    coords: "34°2′30.4″S 18°25′1.5″E",
    location: "Constantia",
    key: "buitenverwachting",
  },
  {
    name: "Cape Point Vineyards",
    coords: "34.09587°S 18.38538°E",
    location: "Constantia",
    key: "capepointvineyards",
  },
  {
    name: "Constantia Glen",
    coords: "34.0151°S 18.4149°E",
    location: "Constantia",
    key: "constantiaglen",
  },
  {
    name: "Constantia Uitsig",
    coords: "34°2′38″S 18°25′21″E",
    location: "Constantia",
    key: "constantiauitsig",
  },
  {
    name: "Eagle's Nest",
    coords: "34.015101°S 18.414951°E",
    location: "Constantia",
    key: "eagle'snest",
  },
  {
    name: "Groot Constantia",
    coords: "34°1′36.5″S 18°25′27.1″E",
    location: "Constantia",
    key: "grootconstantia",
  },
  {
    name: "High Constantia",
    coords: "34.024382°S 18.427116°E",
    location: "Constantia",
    key: "highconstantia",
  },
  {
    name: "Klein Constantia",
    coords: "34°2′19″S 18°24′46.5″E",
    location: "Constantia",
    key: "kleinconstantia",
  },
  {
    name: "Steenberg Vineyards",
    coords: "34.071355°S 18.425549°E",
    location: "Constantia",
    key: "steenbergvineyards",
  },
  {
    name: "Altydgedacht",
    coords: "33°50′45.0″S 18°37′27.4″E",
    location: "Durbanville",
    key: "altydgedacht",
  },
  {
    name: "Antikes",
    coords: "33°49′27.0″S 18°34′52.6″E",
    location: "Durbanville",
    key: "antikes",
  },
  {
    name: "Bloemendal",
    coords: "33°50′22.6″S 18°36′2.8″E",
    location: "Durbanville",
    key: "bloemendal",
  },
  {
    name: "Canto",
    coords: "33°48′19.9″S 18°37′26.3″E",
    location: "Durbanville",
    key: "canto",
  },
  {
    name: "D'Aria",
    coords: "33°50′28.1″S 18°36′34.3″E",
    location: "Durbanville",
    key: "d'aria",
  },
  {
    name: "De Grendel",
    coords: "33°50′37.2″S 18°34′1.8″E",
    location: "Durbanville",
    key: "degrendel",
  },
  {
    name: "De Vallei",
    coords: "33°50′25″S 18°36′46″E",
    location: "Durbanville",
    key: "devallei",
  },
  {
    name: "Diemersdal",
    coords: "33°48′4.5″S 18°38′25.4″E",
    location: "Durbanville",
    key: "diemersdal",
  },
  {
    name: "Durbanville Hills",
    coords: "33°49′29″S 18°33′59″E",
    location: "Durbanville",
    key: "durbanvillehills",
  },
  {
    name: "Groot Phesantekraal",
    coords: "33°47′45″S 18°40′10″E",
    location: "Durbanville",
    key: "grootphesantekraal",
  },
  {
    name: "Hilcrest",
    coords: "33°49′36″S 18°35′29″E",
    location: "Durbanville",
    key: "hilcrest",
  },
  {
    name: "Klein Roosboom",
    coords: "33°49′7″S 18°34′24″E",
    location: "Durbanville",
    key: "kleinroosboom",
  },
  {
    name: "Maastricht",
    coords: "33°48′32.7″S 18°37′31.2″E",
    location: "Durbanville",
    key: "maastricht",
  },
  {
    name: "Meerendal",
    coords: "33°47′56″S 18°37′26″E",
    location: "Durbanville",
    key: "meerendal",
  },
  {
    name: "Nitida",
    coords: "33°50′4″S 18°35′37″E",
    location: "Durbanville",
    key: "nitida",
  },
  {
    name: "Signal Gun",
    coords: "33°49′12″S 18°36′41″E",
    location: "Durbanville",
    key: "signalgun",
  },
  {
    name: "Bouchard Finlayson Winery",
    coords: "34°22′54″S 19°14′30.9″E",
    location: "Elgin and Walkerbay",
    key: "bouchardfinlaysonwinery",
  },
  {
    name: "Charles Fox Cap Classique Wine Estate",
    coords: "34°14′14.9″S 19°4′42.5″E",
    location: "Elgin and Walkerbay",
    key: "charlesfoxcapclassiquewineestate",
  },
  {
    name: "Hamilton Russell Vineyards",
    coords: "34°23′23″S 19°14′30.6″E",
    location: "Elgin and Walkerbay",
    key: "hamiltonrussellvineyards",
  },
  {
    name: "Paul Cluver Estate Wines",
    coords: "34°10′6.2″S 19°5′8.1″E",
    location: "Elgin and Walkerbay",
    key: "paulcluverestatewines",
  },
  {
    name: "Lothian Vineyards",
    coords: "34°11′30″S 18°58′55″E",
    location: "Elgin and Walkerbay",
    key: "lothianvineyards",
  },
  {
    name: "Newton Johnson Family Vineyards",
    coords: "34°22′3.72″S 19°15′34.56″E",
    location: "Elgin and Walkerbay",
    key: "newtonjohnsonfamilyvineyards",
  },
  {
    name: "Akkerdal",
    coords: "33°52′43″S 19°2′57″E",
    location: "Franschhoek",
    key: "akkerdal",
  },
  {
    name: "Allee Bleue Winery",
    coords: "33°51′55″S 18°58′47″E",
    location: "Franschhoek",
    key: "alleebleuewinery",
  },
  {
    name: "Augusta",
    coords: "33°53′35″S 19°5′41″E",
    location: "Franschhoek",
    key: "augusta",
  },
  {
    name: "Atlas Swift",
    coords: "33°54′50″S 19°5′13″E",
    location: "Franschhoek",
    key: "atlasswift",
  },
  {
    name: "Boekenhoutskloof Winery",
    coords: "33°56′33″S 19°6′28″E",
    location: "Franschhoek",
    key: "boekenhoutskloofwinery",
  },
  {
    name: "Boschendal",
    coords: "33°52′39″S 18°58′22″E",
    location: "Franschhoek",
    key: "boschendal",
  },
  {
    name: "Burgundy Bourgogne",
    coords: "33°55′52″S 19°6′41″E",
    location: "Franschhoek",
    key: "burgundybourgogne",
  },
  {
    name: "Cabriere Estate",
    coords: "33°54′44″S 19°7′5″E",
    location: "Franschhoek",
    key: "cabriereestate",
  },
  {
    name: "Chamonix",
    coords: "33°53′58″S 19°7′41″E",
    location: "Franschhoek",
    key: "chamonix",
  },
  {
    name: "Dieu Donne",
    coords: "33°53′48″S 19°7′48″E",
    location: "Franschhoek",
    key: "dieudonne",
  },
  {
    name: "Eikehof",
    coords: "33°53′16″S 19°4′54″E",
    location: "Franschhoek",
    key: "eikehof",
  },
  {
    name: "Elephant Pass",
    coords: "33°55′6″S 19°7′38″E",
    location: "Franschhoek",
    key: "elephantpass",
  },
  {
    name: "Franschhoek",
    coords: "33°54′16″S 19°6′43″E",
    location: "Franschhoek",
    key: "franschhoek",
  },
  {
    name: "Glen Wood",
    coords: "33°54′50″S 19°5′13″E",
    location: "Franschhoek",
    key: "glenwood",
  },
  {
    name: "Grande Provence",
    coords: "33°53′55″S 19°6′12″E",
    location: "Franschhoek",
    key: "grandeprovence",
  },
  {
    name: "Badsberg Wine Cellar",
    coords: "33°50′14″S 18°54′51″E",
    location: "Rawsonville",
    key: "badsbergwinecellar",
  },
  {
    name: "Haute Provence",
    coords: "33°53′49″S 19°6′5″E",
    location: "Franschhoek",
    key: "hauteprovence",
  },
  {
    name: "Jean Daneel",
    coords: "33°54′58″S 19°7′22″E",
    location: "Franschhoek",
    key: "jeandaneel",
  },
  {
    name: "La Cotlog Inn",
    coords: "33°54′26″S 19°7′3″E",
    location: "Franschhoek",
    key: "lacotloginn",
  },
  {
    name: "La Couronne Wine Estate",
    coords: "33°55′13″S 19°6′43″E",
    location: "Franschhoek",
    key: "lacouronnewineestate",
  },
  {
    name: "La Motte",
    coords: "33°52′49.9″S 19°4′28.3″E",
    location: "Franschhoek",
    key: "lamotte",
  },
  {
    name: "Landau Du Val",
    coords: "33°55′12″S 19°6′48″E",
    location: "Franschhoek",
    key: "landauduval",
  },
  {
    name: "La Terra de Luc",
    coords: "33°53′15″S 19°6′43″E",
    location: "Franschhoek",
    key: "laterradeluc",
  },
  {
    name: "Leopard's Leap",
    coords: "33°53′08.7″S 19°04′49″E",
    location: "Franschhoek",
    key: "leopard'sleap",
  },
  {
    name: "Les Chenes",
    coords: "33°53′42″S 19°7′55″E",
    location: "Franschhoek",
    key: "leschenes",
  },
  {
    name: "L'Ormarins Winery",
    coords: "33°52′19″S 18°59′54″E",
    location: "Franschhoek",
    key: "l'ormarinswinery",
  },
  {
    name: "Mont Rochelle",
    coords: "33°54′40″S 19°6′31″E",
    location: "Franschhoek",
    key: "montrochelle",
  },
  {
    name: "Moreson",
    coords: "33°53′14″S 19°3′29″E",
    location: "Franschhoek",
    key: "moreson",
  },
  {
    name: "Rickety Bridge",
    coords: "33°53′57″S 19°5′34″E",
    location: "Franschhoek",
    key: "ricketybridge",
  },
  {
    name: "Rupert & Rothschild Vignerons",
    coords: "33°50′14.5″S 18°56′51.1″E",
    location: "Franschhoek",
    key: "rupert&rothschildvignerons",
  },
  {
    name: "Solms-Delta Wine Estate",
    coords: "33°51′51″S 18°59′23.8″E",
    location: "Franschhoek",
    key: "solms-deltawineestate",
  },
  {
    name: "Stony Brook Vineyards",
    coords: "33°56′23.2″S 19°07′20.6″E",
    location: "Franschhoek",
    key: "stonybrookvineyards",
  },
  {
    name: "Tenfifty Six",
    coords: "33°53′31″S 19°5′32″E",
    location: "Franschhoek",
    key: "tenfiftysix",
  },
  {
    name: "Von Ortloff",
    coords: "33°54′21″S 19°5′59″E",
    location: "Franschhoek",
    key: "vonortloff",
  },
  {
    name: "Vergelegen",
    coords: "34°4′37″S 18°53′30.6″E",
    location: "Helderberg",
    key: "vergelegen",
  },
  {
    name: "Morgenster",
    coords: "",
    location: "Helderberg",
    key: "morgenster",
  },
  {
    name: "Ingwe",
    coords: "",
    location: "Helderberg",
    key: "ingwe",
  },
  {
    name: "Lourensford",
    coords: "",
    location: "Helderberg",
    key: "lourensford",
  },
  {
    name: "Backsberg Estate Cellars",
    coords: "33°49′42.8″S 18°54′53″E",
    location: "Paarl and Wellington",
    key: "backsbergestatecellars",
  },
  {
    name: "Bosman Family Vineyards",
    coords: "33°37′34″S 19°1′29″E",
    location: "Paarl and Wellington",
    key: "bosmanfamilyvineyards",
  },
  {
    name: "Bovlei",
    coords: "33°38′18″S 19°1′36″E",
    location: "Paarl and Wellington",
    key: "bovlei",
  },
  {
    name: "Cape Wine Cellars",
    coords: "33°38′2″S 18°59′37″E",
    location: "Paarl and Wellington",
    key: "capewinecellars",
  },
  {
    name: "Diemersfontein",
    coords: "33°39′38″S 19°00′16″E",
    location: "Paarl and Wellington",
    key: "diemersfontein",
  },
  {
    name: "Drakensig Wine Cellars",
    coords: "33°49′54″S 18°56′48″E",
    location: "Paarl and Wellington",
    key: "drakensigwinecellars",
  },
  {
    name: "D.G.B.",
    coords: "33°37′55″S 18°59′9″E",
    location: "Paarl and Wellington",
    key: "d.g.b.",
  },
  {
    name: "Fairview",
    coords: "33°46′14″S 18°55′41″E",
    location: "Paarl and Wellington",
    key: "fairview",
  },
  {
    name: "Glen Carlou",
    coords: "33°48′34.2″S 18°54′14″E",
    location: "Paarl and Wellington",
    key: "glencarlou",
  },
  {
    name: "Goed Moed",
    coords: "33°45′27″S 18°58′4″E",
    location: "Paarl and Wellington",
    key: "goedmoed",
  },
  {
    name: "Hildebrand",
    coords: "33°39′31″S 19°1′47″E",
    location: "Paarl and Wellington",
    key: "hildebrand",
  },
  {
    name: "Kleinbosch Wines",
    coords: "33°38′2″S 18°59′37″E",
    location: "Paarl and Wellington",
    key: "kleinboschwines",
  },
  {
    name: "Kleine Zalze",
    coords: "33°38′2″S 18°59′37″E",
    location: "Stellenbosch",
    key: "kleinezalze",
  },
  {
    name: "Klein Rhebokskloof",
    coords: "33°39′46″S 19°1′56″E",
    location: "Paarl and Wellington",
    key: "kleinrhebokskloof",
  },
  {
    name: "Mont du Toit",
    coords: "33°39′31.2″S 19°2′2.5″E",
    location: "Paarl and Wellington",
    key: "montdutoit",
  },
  {
    name: "Noble Hill wine estate",
    coords: "33°49′38″S 18°56′18″E",
    location: "Paarl and Wellington",
    key: "noblehillwineestate",
  },
  {
    name: "Plaisir de Merle Winery",
    coords: "33°51′0″S 18°56′36.2″E",
    location: "Paarl and Wellington",
    key: "plaisirdemerlewinery",
  },
  {
    name: "S.F.W.",
    coords: "33°38′32″S 18°59′13″E",
    location: "Paarl and Wellington",
    key: "s.f.w.",
  },
  {
    name: "Upland Organic Estate",
    coords: "33°40′20″S 19°02′38″E",
    location: "Paarl and Wellington",
    key: "uplandorganicestate",
  },
  {
    name: "Vrede en Lust",
    coords: "33°50′15.9″S 18°57′13.4″E",
    location: "Paarl and Wellington",
    key: "vredeenlust",
  },
  {
    name: "Wamakersvallei",
    coords: "33°38′9″S 18°59′25″E",
    location: "Paarl and Wellington",
    key: "wamakersvallei",
  },
  {
    name: "Welgemeend",
    coords: "33°47′51″S 18°53′09″E",
    location: "Paarl and Wellington",
    key: "welgemeend",
  },
  {
    name: "Wellington",
    coords: "33°38′5″S 18°59′26″E",
    location: "Paarl and Wellington",
    key: "wellington",
  },
  {
    name: "Windmeul Kelder",
    coords: "33°40′18″S 18°54′37″E",
    location: "Paarl and Wellington",
    key: "windmeulkelder",
  },
  {
    name: "Ziggurat Winery",
    coords: "33°49′21″S 18°55′47″E",
    location: "Paarl and Wellington",
    key: "zigguratwinery",
  },
  {
    name: "Bon Courage Wine Estate",
    coords: "33°50′43.8″S 19°57′38″E",
    location: "Robertson",
    key: "boncouragewineestate",
  },
  {
    name: "Graham Beck Wine",
    coords: "33°48′14.04″S 19°47′59.78″E",
    location: "Robertson",
    key: "grahambeckwine",
  },
  {
    name: "Rietvallei Wine Estate",
    coords: "33°49′36″S 19°58′38″E",
    location: "Robertson",
    key: "rietvalleiwineestate",
  },
  {
    name: "Rooiberg Winery",
    coords: "33°46′35.3″S 19°45′42.9″E",
    location: "Robertson",
    key: "rooibergwinery",
  },
  {
    name: "Springfield Estate",
    coords: "33°49′44″S 19°54′54″E",
    location: "Robertson",
    key: "springfieldestate",
  },
  {
    name: "Van Loveren",
    coords: "",
    location: "Robertson",
    key: "vanloveren",
  },
  {
    name: "Weltevrede Wine Estate",
    coords: "33°56′30.9″S 20°3′4.4″E",
    location: "Robertson",
    key: "weltevredewineestate",
  },
  {
    name: "Anwilka",
    coords: "",
    location: "Stellenbosch",
    key: "anwilka",
  },
  {
    name: "Beyerskloof Wine Farm",
    coords: "33°53′28″S 18°49′23.6″E",
    location: "Stellenbosch",
    key: "beyerskloofwinefarm",
  },
  {
    name: "Bonfoi",
    coords: "33°53′31″S 18°46′29″E",
    location: "Stellenbosch",
    key: "bonfoi",
  },
  {
    name: "Delheim",
    coords: "33°52′10″S 18°53′8″E",
    location: "Stellenbosch",
    key: "delheim",
  },
  {
    name: "Dornier Wines",
    coords: "33°59′34″S 18°52′13″E",
    location: "Stellenbosch",
    key: "dornierwines",
  },
  {
    name: "Jordan",
    coords: "33°56′34″S 18°44′41″E",
    location: "Stellenbosch",
    key: "jordan",
  },
  {
    name: "Kanonkop",
    coords: "33°51′18.4″S 18°51′36.1″E",
    location: "Stellenbosch",
    key: "kanonkop",
  },
  {
    name: "L'Avenir ( Leavinir )",
    coords: "33°53′18.7″S 18°50′59.1″E",
    location: "Stellenbosch",
    key: "l'avenir(leavinir)",
  },
  {
    name: "Meerlust Estate",
    coords: "34°1′1.7″S 18°45′24.7″E",
    location: "Stellenbosch",
    key: "meerlustestate",
  },
  {
    name: "Mooiplaas Wine Estate",
    coords: "33°54′56″S 18°44′14″E",
    location: "Stellenbosch",
    key: "mooiplaaswineestate",
  },
  {
    name: "De Morgenzon",
    coords: "33°56′28″S 18°46′1″E",
    location: "Stellenbosch",
    key: "demorgenzon",
  },
  {
    name: "Neetlingshof Estate",
    coords: "33°52′26″S 18°48′9″E",
    location: "Stellenbosch",
    key: "neetlingshofestate",
  },
  {
    name: "Overgaauw",
    coords: "33°56′52″S 18°47′37″E",
    location: "Stellenbosch",
    key: "overgaauw",
  },
  {
    name: "Posthouse",
    coords: "-34.01860094445419, 18.811204250571624",
    location: "Stellenbosch",
    key: "posthouse",
  },
  {
    name: "House of J.C. le Roux",
    coords: "-33°54′10″S 18°48′36″E",
    location: "Stellenbosch",
    key: "houseofj.c.leroux",
  },
  {
    name: "Rust en Vrede",
    coords: "-33°59′54″S 18°51′22.5″E",
    location: "Stellenbosch",
    key: "rustenvrede",
  },
  {
    name: "Rustenberg Wines",
    coords: "-33°53′44.8″S 18°53′33.6″E",
    location: "Stellenbosch",
    key: "rustenbergwines",
  },
  {
    name: "Saxenburg",
    coords: "33°56′47.9″S 18°43′9.4″E",
    location: "Stellenbosch",
    key: "saxenburg",
  },
  {
    name: "Simonsig",
    coords: "33°52′12.1″S 18°49′31.7″E",
    location: "Stellenbosch",
    key: "simonsig",
  },
  {
    name: "Spier Wine Farm",
    coords: "33°58′23″S 18°46′56″E",
    location: "Stellenbosch",
    key: "spierwinefarm",
  },
  {
    name: "Stellenzicht",
    coords: "33°59′50″S 18°46′17″E",
    location: "Stellenbosch",
    key: "stellenzicht",
  },
  {
    name: "Thelema Mountain Vineyards",
    coords: "33°54′30″S 18°55′23.4″E",
    location: "Stellenbosch",
    key: "thelemamountainvineyards",
  },
  {
    name: "Dewaal",
    coords: "33°56′30″S 18°55′23.4″E",
    location: "Stellenbosch",
    key: "dewaal",
  },
  {
    name: "Warwick Wine Estate",
    coords: "33°50′26.6″S 18°51′51″E",
    location: "Stellenbosch",
    key: "warwickwineestate",
  },
  {
    name: "Vergenoegd Löw Wine Estate",
    coords: "",
    location: "Stellenbosch",
    key: "vergenoegdlöwwineestate",
  },
  {
    name: "Waterford Estate",
    coords: "33°59′43.1″S 18°52′14.0″E",
    location: "Stellenbosch",
    key: "waterfordestate",
  },
  {
    name: "Zevenwacht Wine Estate",
    coords: "",
    location: "Stellenbosch",
    key: "zevenwachtwineestate",
  },
  {
    name: "Zonnebloem (winery)",
    coords: "",
    location: "Stellenbosch",
    key: "zonnebloem(winery)",
  },
  {
    name: "Allesverloren",
    coords: "33°21′32.5″S 18°52′24.1″E",
    location: "Swartland",
    key: "allesverloren",
  },
  {
    name: "Badenhorst",
    coords: "",
    location: "Swartland",
    key: "badenhorst",
  },
  {
    name: "Lammershoek",
    coords: "33°31′30.2″S 18°48′21.1″E",
    location: "Swartland",
    key: "lammershoek",
  },
  {
    name: "Mullineux",
    coords: "",
    location: "Swartland",
    key: "mullineux",
  },
  {
    name: "Porseleinberg",
    coords: "",
    location: "Swartland",
    key: "porseleinberg",
  },
  {
    name: "The Observatory",
    coords: "",
    location: "Swartland",
    key: "theobservatory",
  },
  {
    name: "The Sadie Family",
    coords: "33°31′31″S 18°48′18.1″E",
    location: "Swartland",
    key: "thesadiefamily",
  },
  {
    name: "Montpellier",
    coords: "33°17′21″S 19°6′22″E",
    location: "Tulbagh",
    key: "montpellier",
  },
  {
    name: "Rijk’s Private Cellar",
    coords: "",
    location: "Tulbagh",
    key: "rijk’sprivatecellar",
  },
  {
    name: "Tulbagh Mountain Vineyards",
    coords: "",
    location: "Tulbagh",
    key: "tulbaghmountainvineyards",
  },
  {
    name: "Twee Jonge Gezellen",
    coords: "33°14′18″S 19°6′46″E",
    location: "Tulbagh",
    key: "tweejongegezellen",
  },
  {
    name: "Groot Eiland Winery",
    coords: "33°39′48″S 19°18′25″E",
    location: "Worcester",
    key: "grooteilandwinery",
  },
  {
    name: "Kleinplasie Wine Cellar",
    coords: "33°38′32″S 19°28′13″E",
    location: "Worcester",
    key: "kleinplasiewinecellar",
  },
  {
    name: "KWV",
    coords: "33°38′8″S 19°27′26″E",
    location: "Worcester",
    key: "kwv",
  },
  {
    name: "Noordboland",
    coords: "33°38′8″S 19°27′45″E",
    location: "Worcester",
    key: "noordboland",
  },
  {
    name: "Stables Wine Estate",
    coords: "29°19′32″S 29°58′48″E",
    location: "KwaZulu-Natal",
    key: "stableswineestate",
  },
  {
    name: "Cathedral Peak Wine Estate",
    coords: "28°50′26″S 29°27′09″E",
    location: "KwaZulu-Natal",
    key: "cathedralpeakwineestate",
  },
];
